# -*- coding: utf-8 -*-
# Author:shihua
# Designer:shihua
# Coder:shihua
# Email:15021408795@163.com
# License: PiggyStudio
# Copyright (c) 2026 PiggyStudio. All rights reserved.



'''
Module Introduction
-------------------

This is a unit test collection of the HouseholderOLSComponent OLS linear regression component

- Design mode:

    (1) nothing

- Key points:

    (1) pytest unit testing framework

    (2) Reproducible simulated data generated by dual fixed random seeds

    (3) The core criterion for the correctness of the algorithm: the deviation between the QR solution and the official lstsq solution is at the machine precision level ($1e-12~1e-16$, i.e. 1e-12~1e-16)

- Main functions:

    (1) Test the correctness of the Householder QR decomposition OLS training link

    (2) Test the correctness of JIT batch prediction inference

Engineering flow closure
------------------------
Standardized reproducible dataset generation -> Householder thin QR decomposition orthogonal transformation -> upper triangular back substitution training to solve weights -> multi-dimensional accuracy verification -> JIT-accelerated batch inference prediction:

    (1) Generate a column full rank design matrix A and observation labels $b = A*x_true + noise$ (b = A·x_true + noise) with dual fixed random seeds

    (2) Train and solve the optimal regression coefficients x_hat through $R*x_hat = Q^T*b$ (R·x̂ = Qᵀ·b)

    (3) Verify the residual 2-norm, the deviation from the preset true values, and the deviation from the official lstsq benchmark

    (4) Batch prediction on the test set through $y_pred = A_test · x_hat$ (y_pred = A_test·x̂), and compare with the noise-free true labels

Usage examples
--------------
.. code-block:: python
    :linenos:

    python -m pytest statjax/tests/test_ols.py -v

Class Description
-----------------
(1)TestHouseholderOLSComponent: This is a unit test class of the HouseholderOLSComponent component, the main function is to test the three unified interfaces of train, reasoning, and _info

References
----------
pytestORG `"pytest documentation"<https://docs.pytest.org/>`_

StatJAX001 OLS Design Document `"StatJAX001 OLS SH V003"<https://github.com/redblue0216/statjax>`_
'''



####### Load Packages ##############################################################################
####################################################################################################



### Basic package
import pytest
### Algorithm package
import jax
import jax.numpy as jnp
### Project Package - Algorithm Components
from statjax.regression import HouseholderOLSComponent



####### Global Parameters ##########################################################################
####################################################################################################



### Enable float64 precision before any JAX array creation
jax.config.update("jax_enable_x64",True)

### Sample size and feature dimension of the simulated dataset
N_TRAIN,P_DIM = 100,5
### Number of test set samples
N_TEST = 10
### Gaussian noise scale, controls the size of data perturbation
NOISE_SCALE = 0.05
### Machine precision threshold: the deviation between the QR solution and the official lstsq solution should be at the 1e-12~1e-16 level
MACHINE_PRECISION_TOL = 1e-10



####### Auxiliary Functions ########################################################################
####################################################################################################



def generate_ols_data(n,p,noise_scale=NOISE_SCALE):
    '''Method Function:

        Define a reproducible and verifiable OLS simulated dataset generation function, the main function is to construct a column full rank design matrix and observation labels with preset true values, the main technical dual fixed random seeds

    :parameters:
        - n (int) - Total number of samples
        - p (int) - Feature dimension
        - noise_scale (float) - Gaussian noise scale, controls the size of data perturbation

    :return:
        - A (jnp.ndarray) - (n,p) Column full rank design matrix
        - b (jnp.ndarray) - (n,) Observation label vector
        - x_true (jnp.ndarray) - (p,) Preset true regression coefficients (for accuracy verification)
    '''

    ### Fix dual random seeds to ensure that the generated data is completely consistent every time, achieving absolute reproducibility
    key_A = jax.random.PRNGKey(0)
    key_noise = jax.random.PRNGKey(1)

    ### Preset true regression weights (true values, used for subsequent quantification of fitting errors)
    x_true = jnp.array([1.2,-2.1,0.7,3.3,-1.5],dtype=jnp.float64)[:p]

    ### Generate a column full rank design matrix subject to Gaussian distribution
    A = jax.random.normal(key_A,(n,p),dtype=jnp.float64)

    ### Generate tiny Gaussian noise to simulate measurement errors in real observation scenarios
    noise = noise_scale * jax.random.normal(key_noise,(n,),dtype=jnp.float64)

    ### Construct standard OLS observation labels: b = A·x_true + noise
    b = A @ x_true + noise

    return A,b,x_true



####### Test Fixtures ##############################################################################
####################################################################################################



@pytest.fixture(scope="module")
def trained_component():
    '''Method Function:

        Define a module-level test fixture, the main function is to provide a trained HouseholderOLSComponent instance and the simulated dataset for all test cases to share

    :parameters:
        nothing

    :return:
        - data (dict) - Dictionary containing the trained component instance, the simulated dataset, and the training results
    '''

    ### Generate the training dataset
    A_train,b_train,x_true = generate_ols_data(N_TRAIN,P_DIM)
    ### Train the OLS model
    component = HouseholderOLSComponent()
    x_hat,metrics = component.train(A=A_train,b=b_train)

    return {
        "component": component,
        "A_train": A_train,
        "b_train": b_train,
        "x_true": x_true,
        "x_hat": x_hat,
        "metrics": metrics
    }



####### Test Classes ###############################################################################
####################################################################################################



class TestHouseholderOLSComponent:
    '''Class Introduction:

        This is a unit test class of the HouseholderOLSComponent component, the main function is to test the three unified interfaces of train, reasoning, and _info
    '''


    def test_train_output_shape(self,trained_component):
        '''Method Function:

            Test whether the shape and precision of the trained regression coefficients meet expectations
        '''

        x_hat = trained_component["x_hat"]
        assert x_hat.shape == (P_DIM,)
        assert x_hat.dtype == jnp.float64


    def test_train_residual(self,trained_component):
        '''Method Function:

            Test whether the fitting residual 2-norm of the training set is at the noise scale level
        '''

        residual_norm = trained_component["metrics"]["residual_norm"]
        ### The residual should be of the same magnitude as noise_scale * sqrt(n), with a loose upper bound
        assert residual_norm < 10 * NOISE_SCALE * jnp.sqrt(N_TRAIN)


    def test_diff_with_lstsq(self,trained_component):
        '''Method Function:

            Test whether the deviation between the QR solution and the official lstsq solution is at the machine precision level, which is the core criterion for the correctness of the algorithm
        '''

        diff_with_lstsq = trained_component["metrics"]["diff_with_lstsq"]
        assert diff_with_lstsq < MACHINE_PRECISION_TOL


    def test_param_close_to_true(self,trained_component):
        '''Method Function:

            Test whether the error norm between the trained regression coefficients and the preset true values is within tolerance
        '''

        param_error = jnp.linalg.norm(trained_component["x_hat"] - trained_component["x_true"])
        assert param_error < 10 * NOISE_SCALE


    def test_reasoning_predict(self,trained_component):
        '''Method Function:

            Test whether the error norm between the batch prediction of the reasoning method and the noise-free true labels of the test set is within tolerance
        '''

        ### Generate the test set feature matrix
        key_test = jax.random.PRNGKey(2)
        A_test = jax.random.normal(key_test,(N_TEST,P_DIM),dtype=jnp.float64)
        ### Calculate the true labels of the test set (no additional noise, for accurate comparison)
        y_test_true = A_test @ trained_component["x_true"]

        ### Batch prediction by the model
        y_pred = trained_component["component"].reasoning(A_test=A_test)

        assert y_pred.shape == (N_TEST,)
        test_pred_error = jnp.linalg.norm(y_pred - y_test_true)
        assert test_pred_error < 10 * NOISE_SCALE * jnp.sqrt(N_TEST)


    def test_reasoning_before_train(self):
        '''Method Function:

            Test whether calling the reasoning method before training throws the expected exception
        '''

        component = HouseholderOLSComponent()
        A_test = jnp.ones((N_TEST,P_DIM),dtype=jnp.float64)
        with pytest.raises(RuntimeError,match="has not been trained yet"):
            component.reasoning(A_test=A_test)


    def test_info(self):
        '''Method Function:

            Test whether the _info method returns a non-empty string
        '''

        info = HouseholderOLSComponent()._info()
        assert isinstance(info,str)
        assert len(info) > 0



##############################################################################################################################################################################
##############################################################################################################################################################################


### End of file
